/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type Mode = 'Learning' | 'Hackathon' | 'Startup';

export interface BaseModeFeedback {
  summary?: string;
  nextSteps?: string[];
  originality?: string | number;
  buildability?: string | number;
  impact?: string | number;
  feasibility?: string | number;
  learningValue?: string | number;
  marketSize?: string | number;
  monetization?: string | number;
  difficultyLevel?: string;
  timeEstimateHours?: string;
  pitchDeck?: string;
  keyRisks?: string[];
  techJustification?: string;
  competitorInsight?: string;
  monetizationModel?: string;
  refinedIdea: {
    title: string;
    oneLiner: string;
    problem: string;
    targetUser: string;
  };
  techStack: {
    frontend?: Array<{ tech: string; reason: string }>;
    backend?: Array<{ tech: string; reason: string }>;
    database?: Array<{ tech: string; reason: string }>;
    infrastructure?: Array<{ tech: string; reason: string }>;
    tools?: Array<{ tech: string; reason: string }>;
    readyLibraries?: Array<{ lib: string; saves: string }>;
    criticalIntegrations?: string[];
    ai?: Array<{ tech: string; reason: string }>;
  };
}

export interface LearningFeedback extends BaseModeFeedback {
  mode: 'Learning';
  learningAnalysis: {
    complexityLevel: string;
    complexityReason: string;
    timeEstimate: string;
    keyConceptsToLearn: string[];
    prerequisiteSkills: string[];
    learningResources: Array<{ topic: string; resource: string }>;
  };
  learningPath: Record<string, string[]>;
  mvpScope: {
    coreFeatures: string[];
    learningMilestones: string[];
    stretchGoals: string[];
  };
  pitfalls: string[];
}

export interface HackathonFeedback extends BaseModeFeedback {
  mode: 'Hackathon';
  hackathonAnalysis: {
    originalityScore: number;
    originalityReason: string;
    buildability: string;
    buildabilityReason: string;
    timeEstimate: string;
    riskFactors: string[];
    demoImpact: string;
  };
  competitiveEdge: {
    similarSolutions: Array<{ name: string; weakness: string }>;
    yourDifferentiator: string;
    marketGap: string;
  };
  mvpScope: {
    mustHave: string[];
    niceToHave: string[];
    outOfScope: string[];
  };
  quickWins: Record<string, string[]>;
  demoStrategy: string;
}

export interface StartupFeedback extends BaseModeFeedback {
  mode: 'Startup';
  marketAnalysis: {
    marketSize: string;
    growthTrend: string;
    targetSegment: string;
    payingWillingness: string;
  };
  competitiveLandscape: {
    directCompetitors: Array<{ name: string; strength: string; weakness: string }>;
    indirectCompetitors: string[];
    yourMoat: string; // Competitive advantage or "moat"
    barriers: string[];
  };
  businessModel: {
    revenueStreams: Array<{ stream: string; potential: string }>;
    unitEconomics: {
      cac: string;
      ltv: string;
      ltvCacRatio: string;
    };
    pricingStrategy: string;
  };
  mvpScope: {
    mustHave: string[];
    validation: string[];
    v1Features: string[];
    outOfScope: string[];
  };
  roadmap: Record<string, string>;
  risks: {
    technical: string[];
    business: string[];
    mitigation: string[];
  };
  fundingStrategy: string;
}

export type IdeaFeedback = LearningFeedback | HackathonFeedback | StartupFeedback;

export interface Project {
  id: string;
  user_id: string;
  title: string;
  description: string;
  mode: Mode;
  refined_idea_json: IdeaFeedback | null;
  github_url?: string;
  teammates?: string[];
  created_at: string;
}

export interface ProjectGithub {
  id: string;
  project_id: string;
  full_name: string;
  description: string | null;
  stars: number;
  language: string | null;
  topics: string[];
  default_branch: string;
  fetched_at: string;
}

export interface GithubContentItem {
  name: string;
  path: string;
  type: "file" | "dir";
  size: number;
}

export interface GithubFileContent {
  content: string;
  size: number;
  sha: string;
}

export interface GithubRepoData {
  fullName: string;
  description: string | null;
  stars: number;
  language: string | null;
  topics: string[];
  defaultBranch: string;
}

export interface GithubPRResult {
  prUrl: string;
  prNumber: number;
}

export interface ProjectFile {
  id: string;
  project_id: string;
  name: string;
  url: string;
  size: number;
  type: string;
  user_id: string;
  created_at: string;
}

export interface ProjectLog {
  id: string;
  project_id: string;
  user_id: string;
  action: string;
  details: Record<string, unknown>; // Specific action details stored as JSON
  created_at: string;
}

export type SpecType = 'Auth' | 'API' | 'Frontend' | 'AI' | 'Infrastructure' | 'Custom';

export interface Spec {
  id: string;
  project_id: string;
  title: string;
  type: SpecType;
  content: string; // Markdown content
  status: 'draft' | 'completed';
  created_at: string;
  embedding?: number[];
}

/**
 * Type for creating a new Spec.
 * Excludes fields generated by the database.
 */
export interface CreateSpecInput {
  project_id: string;
  title: string;
  type: SpecType;
  content: string;
  status?: 'draft' | 'completed';
}

/**
 * Type for updating an existing Spec.
 * All fields are optional except the identifier.
 */
export interface UpdateSpecInput {
  title?: string;
  type?: SpecType;
  content?: string;
  status?: 'draft' | 'completed';
}

export interface Message {
  role: 'user' | 'assistant';
  content: string;
}

export interface Conversation {
  id: string;
  spec_id: string;
  messages: Message[];
  created_at: string;
}
